// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sncxpgjddhxjlcyhjcli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuY3hwZ2pkZGh4amxjeWhqY2xpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3OTI0MzAsImV4cCI6MjA2NTM2ODQzMH0.a95rzPdlfuDbPiJqeVcu_r_RDGjrHimHx1XtwR3LmmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);